$ ->
  $('.one').addClass('span1').removeClass('one')
  $('.two').addClass('span2').removeClass('two')
  $('.three').addClass('span3').removeClass('three')
  $('.four').addClass('span4').removeClass('four')
  $('.five').addClass('span5').removeClass('five')
  $('.six').addClass('span6').removeClass('six')
  $('.seven').addClass('span7').removeClass('seven')
  $('.eight').addClass('span8').removeClass('eight')
  $('.sixteen').addClass('span16').removeClass('sixteen')
  $('header #search-bar form').addClass('navbar-form').addClass('pull-right')
  $('#search-bar form #keywords').addClass('search-query')
  $('aside #sidebar_products_search').addClass('form-inline')
  $('#cart-form form').addClass('form-inline')