$ ->
  $('.one').addClass('span1').removeClass('one')
  $('.two').addClass('span2').removeClass('two')
  $('.three').addClass('span3').removeClass('three')
  $('.four').addClass('span4').removeClass('four')
  $('.five').addClass('span5').removeClass('five')
  $('.six').addClass('span6').removeClass('six')
  $('.seven').addClass('span7').removeClass('seven')
  $('.eight').addClass('span8').removeClass('eight')
  $('.nine').addClass('span9').removeClass('nine')
  $('.ten').addClass('span10').removeClass('ten')
  $('.eleven').addClass('span11').removeClass('eleven')
  $('.twelve').addClass('span12').removeClass('twelve')
  $('.thirteen').addClass('span13').removeClass('thirteen')
  $('.fourteen').addClass('span14').removeClass('fourteen')
  $('.fifteen').addClass('span15').removeClass('fifteen')
  $('.sixteen').addClass('span16').removeClass('sixteen')
  $('header #search-bar form').addClass('navbar-form').addClass('pull-right')
  $('#search-bar form #keywords').addClass('search-query')
  $('aside #sidebar_products_search').addClass('form-inline')
  $('#cart-form form').addClass('form-inline')